name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Thay đổi phiên bản Node.js nếu cần

    - name: Install dependencies
      run: npm install

    - name: Deploy to Firebase
      run: npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
